WITH CTE AS (
SELECT 
TO_TIMESTAMP(STARTED_AT) AS STARTED_AT,
DATE(TO_TIMESTAMP(STARTED_AT)) AS DATE_STARTED_AT,
HOUR(TO_TIMESTAMP(STARTED_AT)) AS HOUR_STARTED_AT,
CASE
WHEN DAYNAME(TO_TIMESTAMP(STARTED_AT)) in ('Sat','Sun')
THEN 'WEEKEND'
ELSE 'BUSINESSDAY'
END AS DAY_TYPE,
CASE
WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) in (12,1,2)
  THEN 'WINTER'
WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) in (3,4,5)
  THEN 'SPRING'
WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) in (6,7,8)
  THEN 'SUMMER'
WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) in (9,10,11)
  THEN 'AUTOMN'
END AS STATION_OF_YEAR
from {{ source('demo', 'bike') }}
where started_at != 'started_at'
)
select *
from CTE
